inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'app/views/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
